name: Deploy to Hostinger VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ vars.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh ${{ vars.VPS_USER }}@${{ vars.VPS_HOST }} << 'EOF'
            cd /ethenugu/landing-page-api
            git pull
            npm install
            pm2 restart ethenugu-landing-page-api || pm2 start npm --name ethenugu-landing-page-api -- start
          EOF
